// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.7.1
// source: api/connect/v1/connect.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	v1 "kratosdemo/api/common/v1"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TestConnect请求
type TestConnectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectRequest) Reset() {
	*x = TestConnectRequest{}
	mi := &file_api_connect_v1_connect_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectRequest) ProtoMessage() {}

func (x *TestConnectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_v1_connect_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectRequest.ProtoReflect.Descriptor instead.
func (*TestConnectRequest) Descriptor() ([]byte, []int) {
	return file_api_connect_v1_connect_proto_rawDescGZIP(), []int{0}
}

// TestConnect响应数据
type TestConnectData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestConnectData) Reset() {
	*x = TestConnectData{}
	mi := &file_api_connect_v1_connect_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestConnectData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestConnectData) ProtoMessage() {}

func (x *TestConnectData) ProtoReflect() protoreflect.Message {
	mi := &file_api_connect_v1_connect_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestConnectData.ProtoReflect.Descriptor instead.
func (*TestConnectData) Descriptor() ([]byte, []int) {
	return file_api_connect_v1_connect_proto_rawDescGZIP(), []int{1}
}

func (x *TestConnectData) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TestConnectData) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_connect_v1_connect_proto protoreflect.FileDescriptor

const file_api_connect_v1_connect_proto_rawDesc = "" +
	"\n" +
	"\x1capi/connect/v1/connect.proto\x12\x0eapi.connect.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1aapi/common/v1/common.proto\"\x14\n" +
	"\x12TestConnectRequest\"E\n" +
	"\x0fTestConnectData\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2o\n" +
	"\aConnect\x12d\n" +
	"\vTestConnect\x12\".api.connect.v1.TestConnectRequest\x1a\x17.api.common.v1.Response\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/connect/testB\x1eZ\x1ckratosdemo/api/connect/v1;v1b\x06proto3"

var (
	file_api_connect_v1_connect_proto_rawDescOnce sync.Once
	file_api_connect_v1_connect_proto_rawDescData []byte
)

func file_api_connect_v1_connect_proto_rawDescGZIP() []byte {
	file_api_connect_v1_connect_proto_rawDescOnce.Do(func() {
		file_api_connect_v1_connect_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_connect_v1_connect_proto_rawDesc), len(file_api_connect_v1_connect_proto_rawDesc)))
	})
	return file_api_connect_v1_connect_proto_rawDescData
}

var file_api_connect_v1_connect_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_connect_v1_connect_proto_goTypes = []any{
	(*TestConnectRequest)(nil), // 0: api.connect.v1.TestConnectRequest
	(*TestConnectData)(nil),    // 1: api.connect.v1.TestConnectData
	(*v1.Response)(nil),        // 2: api.common.v1.Response
}
var file_api_connect_v1_connect_proto_depIdxs = []int32{
	0, // 0: api.connect.v1.Connect.TestConnect:input_type -> api.connect.v1.TestConnectRequest
	2, // 1: api.connect.v1.Connect.TestConnect:output_type -> api.common.v1.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_connect_v1_connect_proto_init() }
func file_api_connect_v1_connect_proto_init() {
	if File_api_connect_v1_connect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_connect_v1_connect_proto_rawDesc), len(file_api_connect_v1_connect_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_connect_v1_connect_proto_goTypes,
		DependencyIndexes: file_api_connect_v1_connect_proto_depIdxs,
		MessageInfos:      file_api_connect_v1_connect_proto_msgTypes,
	}.Build()
	File_api_connect_v1_connect_proto = out.File
	file_api_connect_v1_connect_proto_goTypes = nil
	file_api_connect_v1_connect_proto_depIdxs = nil
}
